---
title: "First Knit"
author: "Danitza Nunez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
 My name is Danitza Nunez, I went to high school at Pasadena High School, my senior year I transferred to Palmdale High School. English has always been easier for me.I did best in English and art class. Math has aways been a difficult subject for me.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have an apple computer.I rate myself a 6. I have sometimes reliable internet access at home on a good day.    
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddy call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Nitza. Short for Danitza.    
   

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     

I want to get my degree  and transfer to UCLA. I think sociology is a subject that i am interested in. I want to obtain my bachelors in Sociology, and eventually work for a non-profit that helps our community.   
   

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I have been to Nicaragua, and Mexico. I would love to visit Greece, and Italy and Germany one day. I travel to many National Parks like zion, Yosemite, the Grand Canyon. I love the outdoors and camping. I have never served in the military, but my husband was in the US NAVY for 11 years. 
   
  

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  

### my answer     
  I am takings statistics to finish my associates degree and transfer. I need to get an A. That is my plan.  
   
 






  




